#! /bin/sh
# Copyright © 2001,2002 Mario Jou/3en <joussen@debian.org>
# Copyright © 2006-2008 Martin F. Krafft <madduck@debian.org>
# Distributable under the terms of the GNU GPL version 2.
#
set -e
case "${1:-}" in
    remove)
	if command -v update-initramfs >/dev/null 2>&1; then
	    update-initramfs -u
	fi
    ;;

  purge)
    rm -f /etc/default/mdadm /etc/mdadm.conf /etc/mdadm/mdadm.conf
    ;;

esac

[ -d /run/systemd/system ] && systemctl --system daemon-reload >/dev/null || :

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mdadm" ] ; then
	chmod -x "/etc/init.d/mdadm" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d mdadm remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mdadm-waitidle" ] ; then
	chmod -x "/etc/init.d/mdadm-waitidle" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d mdadm-waitidle remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.11.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

# v2025.266 by Guenther Brunthaler
thispkg=mdadm-sysvinit-helper
basedir=/usr/share/initramfs-tools
unwanted='hooks/mdadm scripts/local-block/mdadm scripts/local-bottom/mdadm'
cagedir=exile
#
cagedir=$basedir/$cagedir
for unwanted in $unwanted
do
	cage=$cagedir/$unwanted
	unwanted=$basedir/$unwanted
	test ! -e "$cage" && continue
	dpkg-divert --package "$thispkg" --rename \
		--remove "$unwanted"
done
