#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mdadm-waitidle" ] ; then
	chmod +x "/etc/init.d/mdadm-waitidle" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mdadm" ] ; then
	chmod +x "/etc/init.d/mdadm" >/dev/null || true
fi
# End automatically added section

# v2025.266 by Guenther Brunthaler
thispkg=mdadm-sysvinit-helper
basedir=/usr/share/initramfs-tools
unwanted='hooks/mdadm scripts/local-block/mdadm scripts/local-bottom/mdadm'
cagedir=exile
#
cagedir=$basedir/$cagedir
for unwanted in $unwanted
do
	cage=$cagedir/$unwanted
	unwanted=$basedir/$unwanted
	test ! -e "$unwanted" && continue
	mkdir -p -- "`dirname -- "$cage"`"
	dpkg-divert --package "$thispkg" --rename \
		--divert "$cage" --add "$unwanted"
done
