#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/mdadm" ] ; then
	invoke-rc.d --skip-systemd-native mdadm stop || exit 1
fi
# End automatically added section
